version: '2.2'

services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch-node1
    network_mode: "host"
    env_file:
      - elasticsearch.env
    environment:
      - node.name=elasticsearch-node1
      - cluster.name=es-cluster
      - discovery.seed_hosts=["10.170.0.2:9300", "10.170.0.4:9302"]
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.master=false
      - node.data=true
      - node.ingest=true
      - network.host=10.170.0.3
      - http.port=9201
      - transport.port=9301
      - ELASTIC_PASSWORD_FILE=/run/secrets/elasticsearch_password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-node1-data:/usr/share/elasticsearch/data
    secrets:
      - elasticsearch_password
    restart: unless-stopped

secrets:
  elasticsearch_password:
    file: ./password.txt

volumes:
  es-node1-data:
    driver: local

services:
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch-node1
    network_mode: "host"
    env_file:
      - elasticsearch.env
    environment:
      - ELASTIC_PASSWORD_FILE=/run/secrets/elasticsearch_password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-node1-data:/usr/share/elasticsearch/data
    secrets:
      - elasticsearch_password
    restart: unless-stopped

secrets:
  elasticsearch_password:
    file: ./password.txt

volumes:
  es-node1-data:
    driver: local