version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.3
    container_name: kibana
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - "5601:5601"
    networks:
      - es-network
    restart: unless-stopped
    depends_on:
      - elasticsearch

networks:
  es-network:
    driver: bridge